# --- AUTO-INJECTED HARDENING (regenerated by build workflow) ---
import sys, os, atexit, shutil, ctypes, multiprocessing
if hasattr(sys, "frozen"):
    try: multiprocessing.freeze_support()
    except Exception: pass
try:
    _kernel32 = ctypes.windll.kernel32
    _kernel32.CreateMutexW(None, False, "Global\\MnAlqariToolSingletonMutex_v1")
    if _kernel32.GetLastError() == 183:
        ctypes.windll.user32.MessageBoxW(0, "\u062a\u0637\u0628\u064a\u0642 \u0645\u0646 \u0627\u0644\u0642\u0627\u0631\u0626\u061f \u0634\u063a\u0627\u0644 \u0645\u0633\u0628\u0642\u0627\u064b.", "\u062a\u0646\u0628\u064a\u0647", 0x40)
        sys.exit(0)
except Exception:
    pass
def _silent_meipass_cleanup():
    mp = getattr(sys, "_MEIPASS", None)
    if mp and os.path.isdir(mp):
        try: shutil.rmtree(mp, ignore_errors=True)
        except Exception: pass
atexit.register(_silent_meipass_cleanup)
# --- END HARDENING ---

